
LLM = "gpt"
#LLM = "huggingface"
#GPT_MODEL = "gpt-3.5-turbo"
GPT_MODEL = "gpt-3.5-turbo-0125"
#GPT_MODEL = "gpt-4"
HF_MODEL = "HuggingFaceH4/zephyr-7b-beta"
#EMBED_MODEL = "local"
#EMBED_MODEL = "text-embedding-ada-002"
#EMBED_MODEL = "text-embedding-3-small"
#EMBED_MODEL = "text-embedding-3-large"
EMBED_MODEL = "local:BAAI/bge-small-en-v1.5"
#MODE = "query"
#MODE = "chat"
MODE = "agent"
